// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetEvents():Promise<Array<main.PomodoroEvent>>;

export function StartTimer():Promise<void>;

export function StopTimer():Promise<void>;
