// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEvents() {
  return window['go']['main']['App']['GetEvents']();
}

export function StartTimer() {
  return window['go']['main']['App']['StartTimer']();
}

export function StopTimer() {
  return window['go']['main']['App']['StopTimer']();
}
